### ISSUE TITLE
After I source my .vimrc plugin stops working.

### ISSUE THREAD

**Issue by whitesiroi** [lfv89/vim-interestingwords#23]
Thanks for great plugin.

After I source my .vimrc plugin stops working. If quit vim and open it again it does work perfectly. but if I source "nnoremap <leader>so :source ~/dotfiles/.vimrc<CR>:filetype detect<CR>:exe ":echo 'vimrc reloaded'"<CR>" it stops working.

**Comment by lfv89** [comment]
Closing. Let me know if this problem persists.
