### ISSUE TITLE
doesn't work across splits

### ISSUE THREAD

**Issue by yshavit** [lfv89/vim-interestingwords#24]
I did a `:vsp` to split my window. Then, with each window looking at a different part of the same file, I highlighted in one window hoping to see the word highlighted in the other. Instead, it looks like the highlights only take effect within a given window.

**Comment by nedbat** [comment]
I would like this to work as well.  The heart of this plugin is matchadd() which applies to a window, not a buffer.  Perhaps a way to re-apply the highlights to a new window would be possible?

**Comment by nedbat** [comment]
@yshavit I implemented a function to call that will re-apply the colors after a split.  If you try it, let me know what you think: https://github.com/lfv89/vim-interestingwords/issues/25

**Comment by lfv89** [comment]
Thanks to @nedbat work we can close this issue. 

If the fix don't work for anyone let's just open a new one.

**Comment by yshavit** [comment]
Sorry for my delay in replying. This is definitely an improvement! But it doesn't seem to work if the split is already open when I highlight a word, which is probably actually my more common use case.
