### ISSUE TITLE
Not work with neovim in terminal

### ISSUE THREAD

**Issue by adoyle-h** [lfv89/vim-interestingwords#27]
I think it is a bug in PR #26

**Comment by lfv89** [comment]
You are right, it is fixed already.

**Comment by adoyle-h** [comment]
It works. Thanks a lot. @lfv89

**Comment by adolenc** [comment]
I was afraid I was being a tad too clever with that one-liner :D . I think these "fixes" break the plugin for half of neovim users, depending on whether they have `set termguicolors` in their `init.vim` or not.

Let me try coming up with a less hacky fix later tonight.

**Comment by gblock0** [comment]
@adolenc I can confirm that taking out `set termguicolors` allows this plugin to work. Should I make a new issue?

**Comment by adolenc** [comment]
Hey @gblock0, my pull request #28 just got merged in. The plugin _should_ work everywhere now, regardless of `termguicolors`.

**Comment by gblock0** [comment]
Thanks @adolenc! It now highlights correctly which I am thrilled about, so thank you so much for fixing that.

Now I'm having an issue moving to the next word. I can use `n` to go to the next word if its on the same line, but trying to go to the next highlighted word on a different line doesn't work. Also `N` doesn't seem to work at all. I can open a new issue for this if you want.

**Comment by adolenc** [comment]
Sorry for the delay in response. If I remember correctly the `n` and `N` commands were already broken before my patch so I think you should open a new issue for this. Sadly I will have no time at all to work on it in any near future.
